import { type FormEvent, useEffect, useState } from "react";
import { addVolunteerUnavailability, getServingProfile, removeVolunteerUnavailability, saveVolunteerPreference, updateMyProfile, withdrawVolunteerPreference, type ServingProfile, type VolunteerFrequencyPeriod } from "../api";
import { CALENDAR_AVATARS } from "../userCalendarStyle";

export function MyProfile({ onProfileChanged }: { onProfileChanged: () => void }) {
  const [data, setData] = useState<ServingProfile | null>(null);
  const [form, setForm] = useState({ name: "", email: "", username: "", calendar_avatar: "" });
  const [away, setAway] = useState({ starts_on: "", ends_on: "", note: "" });
  const [message, setMessage] = useState<string | null>(null);
  async function load() { const next = await getServingProfile(); setData(next); setForm({ name: next.user.name, email: next.user.email, username: next.user.username, calendar_avatar: next.user.calendar_avatar || "" }); }
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : "Could not load profile.")); }, []);
  async function saveProfile(event: FormEvent) { event.preventDefault(); try { await updateMyProfile({ ...form, calendar_avatar: form.calendar_avatar || null }); await load(); onProfileChanged(); setMessage("Profile saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save profile."); } }
  async function toggleArea(areaKey: string, checked: boolean) { try { if (checked) await saveVolunteerPreference(areaKey, { preferred_frequency: "monthly", frequency_count: 1, frequency_period: "month", availability_notes: null }); else await withdrawVolunteerPreference(areaKey); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update serving interest."); } }
  async function updatePreference(areaKey: string, count: number, period: VolunteerFrequencyPeriod, notes: string | null) { await saveVolunteerPreference(areaKey, { preferred_frequency: period === "week" ? "weekly" : period === "month" ? "monthly" : "quarterly", frequency_count: count, frequency_period: period, availability_notes: notes }); await load(); setMessage("Serving preference saved."); }
  if (!data) return <section className="profile-workspace"><p>{message || "Loading your profile…"}</p></section>;
  return <section className="profile-workspace" aria-label="My profile">
    <form className="profile-card" onSubmit={(event) => void saveProfile(event)}>
      <div className="section-heading"><div><p className="eyebrow">Account</p><h2>My details</h2></div><button className="primary-button" type="submit">Save profile</button></div>
      {message ? <p className="form-message">{message}</p> : null}
      <div className="form-grid"><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Username<input required pattern="[a-z0-9][a-z0-9._-]{1,79}" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value.toLowerCase() })} /></label><fieldset className="role-fieldset"><legend>Avatar</legend><div className="calendar-avatar-options"><label className={!form.calendar_avatar ? "selected" : ""}><input type="radio" checked={!form.calendar_avatar} onChange={() => setForm({ ...form, calendar_avatar: "" })} /><span>Initial</span></label>{CALENDAR_AVATARS.map((avatar) => <label className={form.calendar_avatar === avatar ? "selected" : ""} key={avatar}><input type="radio" checked={form.calendar_avatar === avatar} onChange={() => setForm({ ...form, calendar_avatar: avatar })} /><span>{avatar}</span></label>)}</div></fieldset></div>
    </form>
    <section className="profile-card serving-list-panel"><div className="section-heading"><div><p className="eyebrow">Serving</p><h2>How I can help</h2></div></div><p className="muted-copy">Choose a role or task, then set a realistic workload. Admin sees the same grouped structure.</p><div className="serving-role-groups">{Array.from(new Set(data.areas.map((area) => area.category))).map((category) => <section className="serving-role-group" key={category}><h3>{category}</h3>{data.areas.filter((area) => area.category === category).map((area) => { const pref = data.preferences.find((item) => item.area.key === area.key); return <details className={`serving-role-row ${pref ? "selected" : ""}`} key={area.key}><summary><label onClick={(event) => event.stopPropagation()}><input type="checkbox" checked={Boolean(pref)} onChange={(event) => void toggleArea(area.key, event.target.checked)} /><span><strong>{area.name}</strong><small>{pref ? `${pref.status} · ${pref.frequency_count} per ${pref.frequency_period}` : area.description}</small></span></label></summary>{pref ? <div className="serving-role-details"><div className="frequency-input"><span>Up to</span><input aria-label={`${area.name} frequency`} min="0" max="52" type="number" defaultValue={pref.frequency_count} onBlur={(event) => void updatePreference(area.key, Number(event.target.value), pref.frequency_period, pref.availability_notes)} /><span>per</span><select value={pref.frequency_period} onChange={(event) => void updatePreference(area.key, pref.frequency_count, event.target.value as VolunteerFrequencyPeriod, pref.availability_notes)}><option value="week">week</option><option value="month">month</option><option value="quarter">quarter</option><option value="year">year</option></select></div><label>Notes<textarea defaultValue={pref.availability_notes || ""} onBlur={(event) => void updatePreference(area.key, pref.frequency_count, pref.frequency_period, event.target.value || null)} placeholder="Times that suit, experience, or anything coordinators should know" /></label>{pref.admin_notes ? <p className="field-help">Admin note: {pref.admin_notes}</p> : null}</div> : null}</details>; })}</section>)}</div></section>
    <section className="profile-card"><div className="section-heading"><div><p className="eyebrow">Availability</p><h2>Dates I cannot serve</h2></div></div><form className="availability-entry" onSubmit={async (e) => { e.preventDefault(); await addVolunteerUnavailability({ ...away, note: away.note || null }); setAway({ starts_on: "", ends_on: "", note: "" }); await load(); }}><label>From<input required type="date" value={away.starts_on} onChange={(e) => setAway({ ...away, starts_on: e.target.value })} /></label><label>To<input required type="date" min={away.starts_on} value={away.ends_on} onChange={(e) => setAway({ ...away, ends_on: e.target.value })} /></label><label>Note<input value={away.note} onChange={(e) => setAway({ ...away, note: e.target.value })} /></label><button className="text-button" type="submit">Add dates</button></form><div className="availability-list">{data.unavailable.map((item) => <div key={item.id}><span><strong>{item.starts_on}</strong> to <strong>{item.ends_on}</strong>{item.note ? ` · ${item.note}` : ""}</span><button className="text-button" type="button" onClick={async () => { await removeVolunteerUnavailability(item.id); await load(); }}>Remove</button></div>)}</div></section>
  </section>;
}
