import { type FormEvent, useEffect, useState } from "react";
import { addVolunteerUnavailability, getServingProfile, removeVolunteerUnavailability, saveVolunteerPreference, updateMyProfile, withdrawVolunteerPreference, type ServingProfile, type VolunteerFrequency } from "../api";
import { CALENDAR_AVATARS } from "../userCalendarStyle";

const frequencies: { value: VolunteerFrequency; label: string }[] = [{ value: "weekly", label: "Weekly" }, { value: "monthly", label: "Monthly" }, { value: "quarterly", label: "Every few months" }, { value: "semi_yearly", label: "Twice a year" }, { value: "occasional", label: "Occasionally" }];

export function MyProfile({ onProfileChanged }: { onProfileChanged: () => void }) {
  const [data, setData] = useState<ServingProfile | null>(null);
  const [form, setForm] = useState({ name: "", email: "", username: "", calendar_avatar: "" });
  const [away, setAway] = useState({ starts_on: "", ends_on: "", note: "" });
  const [message, setMessage] = useState<string | null>(null);
  async function load() { const next = await getServingProfile(); setData(next); setForm({ name: next.user.name, email: next.user.email, username: next.user.username, calendar_avatar: next.user.calendar_avatar || "" }); }
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : "Could not load profile.")); }, []);
  async function saveProfile(event: FormEvent) { event.preventDefault(); try { await updateMyProfile({ ...form, calendar_avatar: form.calendar_avatar || null }); await load(); onProfileChanged(); setMessage("Profile saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save profile."); } }
  async function toggleArea(areaKey: string, checked: boolean) { try { if (checked) await saveVolunteerPreference(areaKey, { preferred_frequency: "monthly", availability_notes: null }); else await withdrawVolunteerPreference(areaKey); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update serving interest."); } }
  async function updatePreference(areaKey: string, frequency: VolunteerFrequency, notes: string | null) { await saveVolunteerPreference(areaKey, { preferred_frequency: frequency, availability_notes: notes }); await load(); setMessage("Serving preference saved."); }
  if (!data) return <section className="profile-workspace"><p>{message || "Loading your profile…"}</p></section>;
  return <section className="profile-workspace" aria-label="My profile">
    <form className="profile-card" onSubmit={(event) => void saveProfile(event)}>
      <div className="section-heading"><div><p className="eyebrow">Account</p><h2>My details</h2></div><button className="primary-button" type="submit">Save profile</button></div>
      {message ? <p className="form-message">{message}</p> : null}
      <div className="form-grid"><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Username<input required pattern="[a-z0-9][a-z0-9._-]{1,79}" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value.toLowerCase() })} /></label><fieldset className="role-fieldset"><legend>Avatar</legend><div className="calendar-avatar-options"><label className={!form.calendar_avatar ? "selected" : ""}><input type="radio" checked={!form.calendar_avatar} onChange={() => setForm({ ...form, calendar_avatar: "" })} /><span>Initial</span></label>{CALENDAR_AVATARS.map((avatar) => <label className={form.calendar_avatar === avatar ? "selected" : ""} key={avatar}><input type="radio" checked={form.calendar_avatar === avatar} onChange={() => setForm({ ...form, calendar_avatar: avatar })} /><span>{avatar}</span></label>)}</div></fieldset></div>
    </form>
    <section className="profile-card"><div className="section-heading"><div><p className="eyebrow">Serving</p><h2>How I can help</h2></div></div><p className="muted-copy">Choose areas you are interested in. An administrator will confirm each request before it enters a rota.</p><div className="serving-area-grid">{data.areas.map((area) => { const pref = data.preferences.find((item) => item.area.key === area.key); return <article className={`serving-area ${pref ? "selected" : ""}`} key={area.key}><label className="serving-area-toggle"><input type="checkbox" checked={Boolean(pref)} onChange={(e) => void toggleArea(area.key, e.target.checked)} /><span><strong>{area.name}</strong><small>{area.category} · {pref?.status || "Not volunteered"}</small></span></label><p>{area.description}</p>{pref ? <div className="form-grid single-column"><label>How often<select value={pref.preferred_frequency} onChange={(e) => void updatePreference(area.key, e.target.value as VolunteerFrequency, pref.availability_notes)}>{frequencies.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Notes<textarea defaultValue={pref.availability_notes || ""} onBlur={(e) => void updatePreference(area.key, pref.preferred_frequency, e.target.value || null)} placeholder="Times that suit, experience, or anything the rota coordinator should know" /></label>{pref.admin_notes ? <p className="field-help">Admin note: {pref.admin_notes}</p> : null}</div> : null}</article>; })}</div></section>
    <section className="profile-card"><div className="section-heading"><div><p className="eyebrow">Availability</p><h2>Dates I cannot serve</h2></div></div><form className="availability-entry" onSubmit={async (e) => { e.preventDefault(); await addVolunteerUnavailability({ ...away, note: away.note || null }); setAway({ starts_on: "", ends_on: "", note: "" }); await load(); }}><label>From<input required type="date" value={away.starts_on} onChange={(e) => setAway({ ...away, starts_on: e.target.value })} /></label><label>To<input required type="date" min={away.starts_on} value={away.ends_on} onChange={(e) => setAway({ ...away, ends_on: e.target.value })} /></label><label>Note<input value={away.note} onChange={(e) => setAway({ ...away, note: e.target.value })} /></label><button className="text-button" type="submit">Add dates</button></form><div className="availability-list">{data.unavailable.map((item) => <div key={item.id}><span><strong>{item.starts_on}</strong> to <strong>{item.ends_on}</strong>{item.note ? ` · ${item.note}` : ""}</span><button className="text-button" type="button" onClick={async () => { await removeVolunteerUnavailability(item.id); await load(); }}>Remove</button></div>)}</div></section>
  </section>;
}
